apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd
  namespace: stage-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  namespace: openshift-gitops
  name: openshift-gitops-argocd-application-controller
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-prod
  namespace: openshift-gitops
spec:
  destination:
    namespace: stage-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: webserver/overlays/prod
    repoURL: https://github.com/dstraub/do180-sample.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

