apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-helloworld
  name: php-helloworld
spec:
  selector:
    app: php-helloworld
  type: ClusterIP
  ports:
  - name: php-helloworld
    port: 8080
    protocol: TCP
    targetPort: http

