kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base

namespace: stage-prod

commonLabels:
  app.kubernetes.io/name: webserver

images:
- name: webserver
  newName: quay.io/danielstraub/webserver
  newTag: "2.0"

configMapGenerator:
- name: webserver
  files:
  - env.properties

patches:
- patch: |-
    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: webserver
    spec:
      host: stage-prod.cluster.straubcloud.de
